# ==== General Configuration ====

.PHONY: fmt checkstyle pmd spotbugs lint build clean test image

VERSION ?= 1.0.0
IMAGE_NAME ?= my-bookstore-app
JAVA_VERSION ?= 21

# ==== Main tasks ====

up:          ## Launch full infrastructure stack (backend + DB + MQ + viewers)
	@echo "Starting the infrastructure stack..."
	@docker compose -f ./docker/dev-docker-compose.yml up -d

down:        ## Stop and remove the infrastructure stack
	@echo "Stopping the infrastructure stack..."
	@docker compose -f ./docker/dev-docker-compose.yml down

fmt:               ## Only format code
	@echo "Format code using Spotless..."
	@mvn spotless:apply

pmd:               ## Run PMD analysis (for code style)
	@echo "Running PMD..."
	@mvn pmd:check

spotbugs:          ## Run SpotBugs static analysis (Check byte-code)
	@echo "Running SpotBugs..."
	@mvn spotbugs:spotbugs

lint:              ## Run all static analysis tools
	@echo "Running all linters (Spotless, Checkstyle, PMD, SpotBugs)..."
	@$(MAKE) clean build
	@$(MAKE) fmt
	@$(MAKE) pmd
	@$(MAKE) spotbugs

build:             ## Compile the whole project
	@echo "Compiling the project..."
	@mvn clean install -DskipTests

image:             ## Build Docker image with version tag
	@echo "Building Docker image $(IMAGE_NAME):$(VERSION) with Java $(JAVA_VERSION)"
	@docker build \
		--build-arg VERSION=$(VERSION) \
		--build-arg JDK_VERSION=$(JAVA_VERSION) \
		--build-arg DISTROLESS_VERSION=$(JAVA_VERSION) \
		-t $(IMAGE_NAME):$(VERSION) .

test:              ## Execute tests
	@echo "Executing tests..."
	@mvn test

clean:             ## Clean files generated by Maven
	@echo "Clean the project ..."
	@mvn clean
